services:
  api:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    command: /bin/sh -c 'nodemon -e js,html index.js'
    environment:
    - NB_PARTICULES=500
    links:
    - redis
    network_mode: bridge
    ports:
    - 8080:9000
    restart: unless-stopped
  opengl:
    build:
      context: ./src/NBodyGraphics
      dockerfile: Dockerfile
    environment:
    - NB_PARTICULES=500
    - TIME_SIMULATION=5.0
    links:
    - api
    network_mode: bridge
    volumes:
    - ./src/dependencies/:/nbody/dependencies/
    - ./src/NBodyGraphics/output_dir/:/nbody/output_dir/
  particulecalculator_0:
    build:
      context: ./src/NBodyCalculator
      dockerfile: Dockerfile
    environment:
      FIRSTINDEX: '0'
      LASTINDEX: '250'
    links:
    - api
    network_mode: bridge
    volumes:
    - ./src/dependencies/:/nbody/dependencies/
  particulecalculator_1:
    build:
      context: ./src/NBodyCalculator
      dockerfile: Dockerfile
    environment:
      FIRSTINDEX: '250'
      LASTINDEX: '500'
    links:
    - api
    network_mode: bridge
    volumes:
    - ./src/dependencies/:/nbody/dependencies/
  redis:
    expose:
    - '6379'
    image: redis:6.2-alpine
    network_mode: bridge
    restart: unless-stopped
version: '3'
