name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install libs
        run: |
          sudo apt-get install libglfw3-dev
          sudo apt-get install libglm-dev
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install -y mesa-utils

      - name: Move to NBodyCalculator
        run: cd src/NBodyCalculator

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build-Graphics
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Move to NBodyGraphics
        run: cd src/NBodyGraphics

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build-Graphics
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
